# Generated by Django 5.2.6 on 2026-03-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_confirmation',
            field=models.CharField(choices=[('Pending', 'Waiting for User Feedback'), ('Received', 'Yes, Received'), ('Not Received', "No, Didn't Receive")], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
